exports.greetings = require("./greetings");
exports.stickers = require("./stickers");
exports.fun = require("./fun");
exports.youtube=require("./youtube");
exports.anime=require("./anime");
exports.misc=require("./misc");
exports.movie=require("./movie");
exports.help = require("./help");
exports.groups = require("./groups");